# SPDX-FileCopyrightText: 2026 R28 AI, Inc.
# SPDX-License-Identifier: Apache-2.0

"""Request schemas for the Linear pack.

A GraphQL request has exactly two parts: the document and the variables. The
document is a constant that belongs to the tool, so it lives in
:mod:`~charter.packs.linear.queries` and reaches the wire through ``static_body``.
What is left for a schema to describe is the variables — which is why every
schema here has a single ``variables`` field marked ``Body(envelop=True)``.
``envelop=True`` is what keeps the field's *name* on the wire, and ``variables``
is precisely what the wire calls it.

The modules are the pack's categories, and they are the categories the reference
documentation is grouped by: a tool's category is the module its request model
is declared in.

API Reference: https://linear.app/developers/graphql
"""

from charter.packs.linear.types.attachments import (
    AttachmentCreateRequest,
    AttachmentDeleteRequest,
    AttachmentGetRequest,
    AttachmentsForUrlRequest,
    AttachmentsListRequest,
    AttachmentUpdateRequest,
)
from charter.packs.linear.types.comments import (
    CommentCreateRequest,
    CommentDeleteRequest,
    CommentGetRequest,
    CommentResolveRequest,
    CommentsListRequest,
    CommentUnresolveRequest,
    CommentUpdateRequest,
    ReactionCreateRequest,
    ReactionDeleteRequest,
)
from charter.packs.linear.types.common import (
    BooleanComparator,
    DateComparator,
    IdComparator,
    NullableDateComparator,
    NullableNumberComparator,
    NullableStringComparator,
    NumberComparator,
    PageVariables,
    PaginationOrderBy,
    Priority,
    StringComparator,
)
from charter.packs.linear.types.customers import (
    CustomerCreateRequest,
    CustomerDeleteRequest,
    CustomerGetRequest,
    CustomerNeedCreateRequest,
    CustomerNeedDeleteRequest,
    CustomerNeedsListRequest,
    CustomerNeedUpdateRequest,
    CustomersListRequest,
    CustomerStatusesListRequest,
    CustomerTiersListRequest,
    CustomerUpdateRequest,
)
from charter.packs.linear.types.cycles import (
    CycleArchiveRequest,
    CycleGetRequest,
    CyclesListRequest,
    CycleStartUpcomingCycleTodayRequest,
    CycleUpdateRequest,
)
from charter.packs.linear.types.documents import (
    DocumentCreateRequest,
    DocumentDeleteRequest,
    DocumentGetRequest,
    DocumentsListRequest,
    DocumentUnarchiveRequest,
    DocumentUpdateRequest,
)
from charter.packs.linear.types.filters import (
    AttachmentFilter,
    CommentFilter,
    CustomerFilter,
    CustomerNeedFilter,
    CycleFilter,
    DocumentFilter,
    InitiativeFilter,
    IssueFilter,
    IssueLabelFilter,
    ProjectFilter,
    ProjectMilestoneFilter,
    ProjectUpdateFilter,
    TeamFilter,
    TemplateFilter,
    UserFilter,
    WorkflowStateFilter,
)
from charter.packs.linear.types.inbox import (
    CustomViewCreateRequest,
    CustomViewDeleteRequest,
    CustomViewGetRequest,
    CustomViewsListRequest,
    FavoriteCreateRequest,
    FavoriteDeleteRequest,
    FavoritesListRequest,
    FavoriteUpdateRequest,
    NotificationArchiveRequest,
    NotificationGetRequest,
    NotificationMarkReadAllRequest,
    NotificationsListRequest,
    NotificationUnarchiveRequest,
    NotificationUpdateRequest,
)
from charter.packs.linear.types.initiatives import (
    InitiativeArchiveRequest,
    InitiativeCreateRequest,
    InitiativeDeleteRequest,
    InitiativeGetRequest,
    InitiativesListRequest,
    InitiativeStatus,
    InitiativeToProjectCreateRequest,
    InitiativeToProjectDeleteRequest,
    InitiativeUnarchiveRequest,
    InitiativeUpdateCreateRequest,
    InitiativeUpdateRequest,
    InitiativeUpdatesListRequest,
)
from charter.packs.linear.types.issues import (
    IssueAddLabelRequest,
    IssueArchiveRequest,
    IssueBatchUpdateRequest,
    IssueCreateRequest,
    IssueDeleteRequest,
    IssueGetRequest,
    IssueRelationCreateRequest,
    IssueRelationDeleteRequest,
    IssueRelationGetRequest,
    IssueRelationsListRequest,
    IssueRelationType,
    IssueRelationUpdateRequest,
    IssueRemoveLabelRequest,
    IssuesListRequest,
    IssueSubscribeRequest,
    IssueUnarchiveRequest,
    IssueUnsubscribeRequest,
    IssueUpdateRequest,
)
from charter.packs.linear.types.labels import (
    IssueLabelCreateRequest,
    IssueLabelDeleteRequest,
    IssueLabelGetRequest,
    IssueLabelsListRequest,
    IssueLabelUpdateRequest,
    ProjectLabelsListRequest,
)
from charter.packs.linear.types.projects import (
    DateResolutionType,
    ProjectAddLabelRequest,
    ProjectCreateRequest,
    ProjectDeleteRequest,
    ProjectGetRequest,
    ProjectHealth,
    ProjectMilestoneCreateRequest,
    ProjectMilestoneDeleteRequest,
    ProjectMilestoneGetRequest,
    ProjectMilestonesListRequest,
    ProjectMilestoneUpdateRequest,
    ProjectRemoveLabelRequest,
    ProjectsListRequest,
    ProjectStatusesListRequest,
    ProjectUnarchiveRequest,
    ProjectUpdateArchiveRequest,
    ProjectUpdateCreateRequest,
    ProjectUpdateGetRequest,
    ProjectUpdateRequest,
    ProjectUpdatesListRequest,
    ProjectUpdateUpdateRequest,
)
from charter.packs.linear.types.search import (
    SearchDocumentsRequest,
    SearchIssuesRequest,
    SearchProjectsRequest,
)
from charter.packs.linear.types.webhooks import (
    WebhookCreateRequest,
    WebhookDeleteRequest,
    WebhookGetRequest,
    WebhooksListRequest,
    WebhookUpdateRequest,
)
from charter.packs.linear.types.workspace import (
    OrganizationRequest,
    TeamGetRequest,
    TeamMembershipCreateRequest,
    TeamMembershipDeleteRequest,
    TeamMembershipGetRequest,
    TeamMembershipsListRequest,
    TeamMembershipUpdateRequest,
    TeamsListRequest,
    UserGetRequest,
    UsersListRequest,
    ViewerRequest,
    WorkflowStateArchiveRequest,
    WorkflowStateCreateRequest,
    WorkflowStateGetRequest,
    WorkflowStatesListRequest,
    WorkflowStateUpdateRequest,
)

__all__ = [
    # shared
    "StringComparator",
    "NullableStringComparator",
    "IdComparator",
    "NumberComparator",
    "NullableNumberComparator",
    "DateComparator",
    "NullableDateComparator",
    "BooleanComparator",
    "PageVariables",
    "PaginationOrderBy",
    "Priority",
    # filters
    "IssueFilter",
    "WorkflowStateFilter",
    "UserFilter",
    "TeamFilter",
    "ProjectFilter",
    "CommentFilter",
    "IssueLabelFilter",
    "CycleFilter",
    "InitiativeFilter",
    "DocumentFilter",
    "AttachmentFilter",
    "CustomerFilter",
    "CustomerNeedFilter",
    "ProjectMilestoneFilter",
    "TemplateFilter",
    "ProjectUpdateFilter",
    # enums
    "IssueRelationType",
    "InitiativeStatus",
    "ProjectHealth",
    "DateResolutionType",
    # issues
    "IssuesListRequest",
    "IssueGetRequest",
    "IssueCreateRequest",
    "IssueUpdateRequest",
    "IssueDeleteRequest",
    "IssueArchiveRequest",
    "IssueUnarchiveRequest",
    "IssueAddLabelRequest",
    "IssueRemoveLabelRequest",
    "IssueSubscribeRequest",
    "IssueUnsubscribeRequest",
    "IssueBatchUpdateRequest",
    "IssueRelationsListRequest",
    "IssueRelationGetRequest",
    "IssueRelationCreateRequest",
    "IssueRelationUpdateRequest",
    "IssueRelationDeleteRequest",
    # comments and reactions
    "CommentsListRequest",
    "CommentGetRequest",
    "CommentCreateRequest",
    "CommentUpdateRequest",
    "CommentDeleteRequest",
    "CommentResolveRequest",
    "CommentUnresolveRequest",
    "ReactionCreateRequest",
    "ReactionDeleteRequest",
    # labels
    "IssueLabelsListRequest",
    "IssueLabelGetRequest",
    "IssueLabelCreateRequest",
    "IssueLabelUpdateRequest",
    "IssueLabelDeleteRequest",
    "ProjectLabelsListRequest",
    # workspace
    "ViewerRequest",
    "OrganizationRequest",
    "TeamsListRequest",
    "TeamGetRequest",
    "UsersListRequest",
    "UserGetRequest",
    "WorkflowStatesListRequest",
    "WorkflowStateGetRequest",
    "WorkflowStateCreateRequest",
    "WorkflowStateUpdateRequest",
    "WorkflowStateArchiveRequest",
    "TeamMembershipsListRequest",
    "TeamMembershipGetRequest",
    "TeamMembershipCreateRequest",
    "TeamMembershipUpdateRequest",
    "TeamMembershipDeleteRequest",
    # projects
    "ProjectsListRequest",
    "ProjectGetRequest",
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectDeleteRequest",
    "ProjectUnarchiveRequest",
    "ProjectAddLabelRequest",
    "ProjectRemoveLabelRequest",
    "ProjectStatusesListRequest",
    "ProjectMilestonesListRequest",
    "ProjectMilestoneGetRequest",
    "ProjectMilestoneCreateRequest",
    "ProjectMilestoneUpdateRequest",
    "ProjectMilestoneDeleteRequest",
    "ProjectUpdatesListRequest",
    "ProjectUpdateGetRequest",
    "ProjectUpdateCreateRequest",
    "ProjectUpdateUpdateRequest",
    "ProjectUpdateArchiveRequest",
    # cycles
    "CyclesListRequest",
    "CycleGetRequest",
    "CycleUpdateRequest",
    "CycleArchiveRequest",
    "CycleStartUpcomingCycleTodayRequest",
    # initiatives
    "InitiativesListRequest",
    "InitiativeGetRequest",
    "InitiativeCreateRequest",
    "InitiativeUpdateRequest",
    "InitiativeDeleteRequest",
    "InitiativeArchiveRequest",
    "InitiativeUnarchiveRequest",
    "InitiativeToProjectCreateRequest",
    "InitiativeToProjectDeleteRequest",
    "InitiativeUpdatesListRequest",
    "InitiativeUpdateCreateRequest",
    # documents
    "DocumentsListRequest",
    "DocumentGetRequest",
    "DocumentCreateRequest",
    "DocumentUpdateRequest",
    "DocumentDeleteRequest",
    "DocumentUnarchiveRequest",
    # attachments
    "AttachmentsListRequest",
    "AttachmentGetRequest",
    "AttachmentsForUrlRequest",
    "AttachmentCreateRequest",
    "AttachmentUpdateRequest",
    "AttachmentDeleteRequest",
    # customers
    "CustomersListRequest",
    "CustomerGetRequest",
    "CustomerCreateRequest",
    "CustomerUpdateRequest",
    "CustomerDeleteRequest",
    "CustomerNeedsListRequest",
    "CustomerNeedCreateRequest",
    "CustomerNeedUpdateRequest",
    "CustomerNeedDeleteRequest",
    "CustomerStatusesListRequest",
    "CustomerTiersListRequest",
    # inbox
    "NotificationsListRequest",
    "NotificationGetRequest",
    "NotificationUpdateRequest",
    "NotificationArchiveRequest",
    "NotificationUnarchiveRequest",
    "NotificationMarkReadAllRequest",
    "FavoritesListRequest",
    "FavoriteCreateRequest",
    "FavoriteUpdateRequest",
    "FavoriteDeleteRequest",
    "CustomViewsListRequest",
    "CustomViewGetRequest",
    "CustomViewCreateRequest",
    "CustomViewDeleteRequest",
    # search
    "SearchIssuesRequest",
    "SearchProjectsRequest",
    "SearchDocumentsRequest",
    # webhooks
    "WebhooksListRequest",
    "WebhookGetRequest",
    "WebhookCreateRequest",
    "WebhookUpdateRequest",
    "WebhookDeleteRequest",
]
