#!/usr/bin/env python
"""Regenerate the per-tool reference under ``docs/packs/<pack>/``.

``generate_pack_docs.py`` writes the pack *page* — the prose, the wire table,
the list of tool names. This writes the layer under it: for every tool, each
argument it accepts with the description the tool publishes and the constraints
that survived, and for every object and enum those arguments reach, one table
naming its fields. The description is the provider's own text plus any ``Gloss``
the pack declares, because it is read from the schema the model receives.

Three things shape the output, and each of them is a decision worth stating.

**Tables, not a schema explorer.** An argument list is a table — name, type,
description — and a reader comparing two tools reads two tables faster than
they open two trees of disclosure triangles. The type is a link, so the table
stays three columns wide however deep the model goes.

**One page per category, not per object.** ``Event`` alone pulls fifteen nested
models; a pack that covered all of Google Calendar would run to some hundreds.
Hundreds of sidebar entries is not navigation, and hundreds of page loads to
read one model is not reading. So every object and enum a category uses lands
on that category's ``objects`` page as an anchored section, and a type link is
a jump within the page a reader is already on.

**The category is derived, never declared.** A tool's category is the module
its request model is declared in: ``EventsListRequest`` lives in
``charter.packs.gcalendar.types.event.actions``, so it is an ``event`` tool.
Packs were already organised that way, which is the point — a declared list
beside ``TOOLS`` is a second place to update and therefore a place to drift.
A pack that keeps its types in one module gets one category, and the level is
dropped rather than rendered as a group of one.

Enums are named the same way. Pydantic inlines a ``Literal`` alias, so the name
the author chose is gone by the time the schema is built. It is recovered by
scanning the pack's type modules for module-level ``Literal`` bindings and
matching on the values. That makes it the author's call: name a ``Literal`` at
module level and it earns a section, an anchor and a link from every field that
uses it; leave it inline and it renders inline, which for two values is what it
deserves.

Usage::

    uv run python scripts/generate_pack_specs.py            # rewrite the pages
    uv run python scripts/generate_pack_specs.py --check    # exit 1 if stale
"""

from __future__ import annotations

import importlib
import json
import pkgutil
import re
import sys
from dataclasses import dataclass
from dataclasses import field as dc_field
from pathlib import Path
from types import ModuleType
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

from pydantic import BaseModel
from pydantic.alias_generators import to_camel
from typing_extensions import get_args, get_origin

from charter.mcp import PACKS
from charter.tool import Tool
from charter.types.markers import Case, Format, Mode

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
PACK_DOCS = DOCS / "packs"

_SCRIPT = "scripts/generate_pack_specs.py"
_BANNER = f"{{/* generated by {_SCRIPT} — do not edit by hand */}}"

# The suffix ``create_llm_schema`` gives a model it derives. A def named
# ``Event_LLM`` is the LLM's view of the wire model ``Event``, and that is how a
# marker declared on the wire finds the property it belongs to.
_LLM_SUFFIX = "_LLM"

# An unnamed inline enum wider than this is not a type a reader can hold in a
# table cell. Its values move to the description and the cell says `string`.
_INLINE_ENUM_MAX = 4

# A blank line, or one holding only the indentation a docstring was written
# with. See the use site in object_section for why both have to count.
_PARAGRAPH_BREAK = re.compile(r"\n[ \t]*\n")

# -----------------------------------------------------
# MDX escaping
# -----------------------------------------------------

# MDX parses `{` as the start of an expression and `<` as the start of a tag, so
# provider prose — which is full of `{calendarId}` and `<= 250` — has to be
# escaped anywhere it lands outside a code span.
_MDX_ESCAPES = {"{": "&#123;", "}": "&#125;", "<": "&lt;", ">": "&gt;"}


def mdx(text: str) -> str:
    """One-line prose, safe to drop into MDX and into a table cell."""
    text = " ".join(str(text).split())
    for raw, entity in _MDX_ESCAPES.items():
        text = text.replace(raw, entity)
    return text.replace("|", "\\|")


def code(text: str) -> str:
    """A code span. Its contents are never parsed, so nothing is escaped."""
    return f"`{text}`"


def jsx_string(text: str) -> str:
    """A string as a JSX expression, for text that must survive verbatim.

    Entities are not decoded inside a Mintlify ``<code>`` element, so a route
    escaped with ``&#123;`` renders the entity rather than the brace. A string
    literal in an expression is the one form MDX passes through untouched.
    """
    return "{" + json.dumps(str(text)) + "}"


# -----------------------------------------------------
# Packs, categories, and where a model lives
# -----------------------------------------------------


def pack_module(pack: str) -> ModuleType:
    return importlib.import_module(f"charter.packs.{pack}")


def _types_root(pack: str) -> str:
    return f"charter.packs.{pack}.types"


def category_of(model: Any, pack: str) -> Optional[str]:
    """The category slug for anything declared under the pack's ``types``.

    ``charter.packs.gmail.types.message.models`` is ``message``; a model in
    ``types/__init__.py`` has no category, and a pack whose models all land
    there is rendered flat. Takes a class or the module itself, which name the
    module they live in differently.
    """
    root = _types_root(pack)
    module = model.__name__ if isinstance(model, ModuleType) else getattr(model, "__module__", "")
    if not module.startswith(root):
        return None
    rest = module[len(root) :].lstrip(".")
    slug = rest.split(".")[0]
    return slug or None


def category_title(pack: str, slug: str) -> str:
    """The category's display name.

    Derived from the slug, unless the category package names itself. Google
    spells it ``calendarList`` and the module has to be ``calendar_list``, so
    ``__title__`` in the category's ``__init__.py`` settles the difference.
    """
    try:
        module = importlib.import_module(f"{_types_root(pack)}.{slug}")
    except ImportError:
        module = None
    declared = getattr(module, "__title__", None)
    if declared:
        return str(declared)
    words = slug.split("_")
    return " ".join([words[0].capitalize(), *words[1:]])


def categorised(pack: str, tools: Sequence[Tool]) -> List[Tuple[Optional[str], List[Tool]]]:
    """The pack's tools, grouped by the module their request models live in.

    Insertion-ordered, so the sidebar follows the order ``TOOLS`` declares.
    A pack with a single category is returned under ``None`` — one group named
    after the only thing in it is a level that says nothing.
    """
    groups: Dict[Optional[str], List[Tool]] = {}
    for tool in tools:
        groups.setdefault(category_of(tool.args_schema, pack), []).append(tool)
    if len(groups) == 1:
        return [(None, next(iter(groups.values())))]
    return list(groups.items())


# -----------------------------------------------------
# Named enums, recovered from the type modules
# -----------------------------------------------------


@dataclass(frozen=True)
class NamedEnum:
    name: str
    values: Tuple[str, ...]
    category: Optional[str]


def _literal_values(annotation: Any) -> Optional[Tuple[str, ...]]:
    from typing import Literal

    if get_origin(annotation) is Literal:
        args = get_args(annotation)
        if args and all(isinstance(arg, str) for arg in args):
            return tuple(args)
    return None


def named_enums(pack: str) -> Dict[Tuple[str, ...], NamedEnum]:
    """Every module-level ``Literal`` alias in the pack, keyed by its values.

    Two aliases that spell the same values are the same enum as far as a
    schema can tell, so the first one declared wins and both fields link to it.
    """
    found: Dict[Tuple[str, ...], NamedEnum] = {}
    root = importlib.import_module(_types_root(pack))
    modules = [root]
    for info in pkgutil.walk_packages(root.__path__, prefix=f"{_types_root(pack)}."):
        try:
            modules.append(importlib.import_module(info.name))
        except ImportError:
            continue

    for module in modules:
        for name, value in vars(module).items():
            if name.startswith("_"):
                continue
            values = _literal_values(value)
            if values is None or values in found:
                continue
            # Re-exported aliases keep the defining module's category.
            found[values] = NamedEnum(name, values, category_of(module, pack))
    return found


# -----------------------------------------------------
# Walking a model's tree
# -----------------------------------------------------


def _referenced_models(annotation: Any) -> Iterable[type]:
    """Every ``BaseModel`` inside an annotation, however deeply parameterised."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        yield annotation
        return
    for arg in get_args(annotation):
        yield from _referenced_models(arg)


def model_tree(model: type, seen: Optional[Set[type]] = None) -> List[type]:
    """``model`` and everything reachable from it, in declaration order."""
    seen = set() if seen is None else seen
    if model in seen:
        return []
    seen.add(model)
    out = [model]
    for field in model.model_fields.values():
        for nested in _referenced_models(field.annotation):
            out.extend(model_tree(nested, seen))
    return out


def direct_children(model: type) -> List[type]:
    """The models one hop from ``model``, deduplicated, in declaration order."""
    out: List[type] = []
    for field in model.model_fields.values():
        for nested in _referenced_models(field.annotation):
            if nested not in out:
                out.append(nested)
    return out


# -----------------------------------------------------
# Markers, as pills
# -----------------------------------------------------


def _pills(field: Any) -> List[Tuple[str, str]]:
    """The markers on one field that are worth showing beside its type.

    ``Path``/``Query``/``Body`` are deliberately absent: the page heads each
    table with where the value lands, so a ``query`` pill under "Query
    parameters" is noise. What is left is the part no other catalogue prints —
    that a value is re-encoded on the way out, that it is accepted but never
    returned, that its key is spelled differently from the rest of the pack.
    """
    modes: Set[str] = set()
    for marker in field.metadata:
        if isinstance(marker, Mode):
            modes |= marker.modes
    if modes & {"response_only", "disabled"}:
        # Dropped from the LLM view before the schema is built. A pill for it
        # would describe a field the caller cannot set.
        return []

    pills: List[Tuple[str, str]] = []
    for marker in field.metadata:
        if isinstance(marker, Format):
            pills.append(("transform", marker.transform))
        elif isinstance(marker, Case):
            pills.append(("case", marker.case))
    for mode in sorted(modes):
        pills.append(("mode", mode))
    return pills


def marker_map(model: type) -> Dict[type, Dict[str, List[Tuple[str, str]]]]:
    """``{wire model: {camelCase property: pills}}`` for a whole tree."""
    out: Dict[type, Dict[str, List[Tuple[str, str]]]] = {}
    for node in model_tree(model):
        here = {to_camel(name): _pills(f) for name, f in node.model_fields.items()}
        out[node] = {name: pills for name, pills in here.items() if pills}
    return out


def render_pills(pills: Sequence[Tuple[str, str]]) -> str:
    if not pills:
        return ""
    spans = "".join(
        f'<span className="marker" data-marker="{kind}">{mdx(value)}</span>' for kind, value in pills
    )
    return f'<br /><span className="markers">{spans}</span>'


# -----------------------------------------------------
# Rendering one type
# -----------------------------------------------------


@dataclass
class Context:
    """What a type needs in order to render itself as a link."""

    pack: str
    category: Optional[str]
    enums: Dict[Tuple[str, ...], NamedEnum]
    # Which category page each enum is published on, filled in at first use and
    # shared across the pack's categories so the second user links to the first.
    enum_homes: Dict[Tuple[str, ...], Optional[str]] = dc_field(default_factory=dict)
    # The objects page currently being rendered, if any. A link is shortened to
    # a bare anchor only when its target is a heading on this very page.
    page: Optional[str] = None
    # LLM def name (``Event_LLM``) -> the wire model it came from.
    models: Dict[str, type] = dc_field(default_factory=dict)
    # Which category page each wire model is published on.
    homes: Dict[type, Optional[str]] = dc_field(default_factory=dict)
    # Named enums some rendered field actually reached, filled in as we go.
    used: Set[Tuple[str, ...]] = dc_field(default_factory=set)


def anchor(name: str) -> str:
    """Mintlify's anchor for a heading, which is the heading slugified.

    An underscore survives the slug; every other run of punctuation becomes a
    hyphen. That asymmetry is load-bearing rather than cosmetic: the shipped
    ``/reference/tool#tool-llm_schema`` is the anchor for ``Tool.llm_schema``,
    so the dot became a hyphen and the underscore did not. No generated heading
    contains one today, which is why folding them was invisible here.
    """
    return re.sub(r"[^a-z0-9_]+", "-", name.lower()).strip("-")


def objects_page(pack: str, category: Optional[str]) -> str:
    return f"packs/{pack}/{category}/objects" if category else f"packs/{pack}/objects"


def tool_page_path(pack: str, tool: Tool) -> str:
    """Where one tool's page is published.

    ``generate_pack_docs.py`` links the pack page's tool list here, and
    ``tests/test_pack_specs.py`` holds the two together.
    """
    category = category_of(tool.args_schema, pack)
    module = pack_module(pack)
    if len(categorised(pack, list(module.TOOLS))) == 1:
        category = None
    return f"/packs/{pack}/{category}/{tool.name}" if category else f"/packs/{pack}/{tool.name}"


def href_to(ctx: Context, name: str, home: Optional[str]) -> str:
    """Where an object or enum section lives, from wherever we are now."""
    page = objects_page(ctx.pack, home)
    fragment = f"#{anchor(name)}"
    return fragment if page == ctx.page else f"/{page}{fragment}"


def link_to(ctx: Context, name: str, home: Optional[str]) -> str:
    """A markdown link to an object or enum section."""
    return f"[{name}]({href_to(ctx, name, home)})"


def link_html(ctx: Context, name: str, home: Optional[str]) -> str:
    """The same link as an anchor, for the tree, where MDX parses no markdown."""
    return f'<a href="{href_to(ctx, name, home)}">{name}</a>'


def _enum_of(node: Dict[str, Any]) -> Optional[List[str]]:
    values = node.get("enum")
    if isinstance(values, list) and all(isinstance(v, str) for v in values):
        return values
    return None


def render_type(ctx: Context, node: Dict[str, Any]) -> Tuple[str, List[str]]:
    """One schema node as a type cell, plus any notes it pushed to the description.

    Returns ``(cell, notes)``. A wide unnamed enum is the only thing that pushes:
    ten string literals do not fit a type column, so the cell says ``string`` and
    the values go to the description.
    """
    notes: List[str] = []

    ref = node.get("$ref")
    if ref:
        def_name = ref.rsplit("/", 1)[1]
        model = ctx.models.get(def_name)
        if model is not None:
            wire = model.__name__
            return link_to(ctx, wire, ctx.homes.get(model)), notes
        return code(def_name.removesuffix(_LLM_SUFFIX)), notes

    if "anyOf" in node:
        # ``Optional[X]`` is the overwhelming case, and "or null" on two thirds
        # of every table is a column of noise. The tables mark what is required;
        # nullability is the complement of that and is not repeated here.
        variants = [v for v in node["anyOf"] if v.get("type") != "null"]
        if len(variants) == 1:
            return render_type(ctx, variants[0])
        cells = []
        for variant in variants:
            cell, extra = render_type(ctx, variant)
            cells.append(cell)
            notes.extend(extra)
        return " \\| ".join(cells), notes

    values = _enum_of(node)
    if values is not None:
        known = ctx.enums.get(tuple(values))
        if known is not None:
            ctx.used.add(known.values)
            home = ctx.enum_homes.setdefault(known.values, ctx.category)
            return link_to(ctx, known.name, home), notes
        if len(values) <= _INLINE_ENUM_MAX:
            return code(" \\| ".join(f'"{v}"' for v in values)), notes
        notes.append("One of " + ", ".join(code(v) for v in values) + ".")
        return code("string"), notes

    kind = node.get("type")
    if kind == "array":
        inner, extra = render_type(ctx, node.get("items", {}))
        notes.extend(extra)
        return f"{inner}[]", notes
    if kind == "object":
        extra_props = node.get("additionalProperties")
        if isinstance(extra_props, dict):
            inner, more = render_type(ctx, extra_props)
            notes.extend(more)
            return f"map of {inner}", notes
        return code("object"), notes
    if kind is None:
        return code("any"), notes
    return code(str(kind)), notes


_CONSTRAINTS = [
    ("minLength", "min length {}"),
    ("maxLength", "max length {}"),
    ("minimum", "≥ {}"),
    ("exclusiveMinimum", "> {}"),
    ("maximum", "≤ {}"),
    ("exclusiveMaximum", "< {}"),
    ("minItems", "min {} items"),
    ("maxItems", "max {} items"),
    ("pattern", "matches `{}`"),
    ("format", "format `{}`"),
]


def constraints_of(node: Dict[str, Any]) -> List[str]:
    """The bounds the provider declared, flattened out of any ``anyOf``."""
    nodes = [node, *[v for v in node.get("anyOf", []) if v.get("type") != "null"]]
    out: List[str] = []
    for candidate in nodes:
        for key, template in _CONSTRAINTS:
            if key in candidate:
                rendered = template.format(candidate[key])
                if rendered not in out:
                    out.append(rendered)
    return out


def describe(node: Dict[str, Any], notes: Sequence[str]) -> str:
    """The description cell: the provider's prose, then what bounds it."""
    parts: List[str] = []
    description = node.get("description")
    if description:
        parts.append(mdx(description))
    parts.extend(notes)

    bounds = constraints_of(node)
    default = node.get("default")
    if default is not None:
        bounds.append(f"defaults to `{json.dumps(default)}`")
    if bounds:
        parts.append(f'<span className="field-constraints">{mdx("; ".join(bounds))}</span>')
    return " ".join(parts) or "—"


# -----------------------------------------------------
# Tables
# -----------------------------------------------------


def field_rows(
    ctx: Context,
    properties: Dict[str, Any],
    required: Set[str],
    pills: Dict[str, List[Tuple[str, str]]],
) -> List[str]:
    rows = []
    for name, node in properties.items():
        cell, notes = render_type(ctx, node)
        flag = (
            ' <span className="required" title="required">*</span>' if name in required else ""
        )
        rows.append(
            f"| {code(name)}{flag} | {cell}{render_pills(pills.get(name, []))} | {describe(node, notes)} |"
        )
    return rows


def table(rows: Sequence[str]) -> str:
    """A field table, wrapped so the stylesheet can find it.

    A markdown table carries no class, and the column widths these tables want
    are not the widths a hand-written table on a pack page wants. The wrapper is
    what separates them; the blank lines are what keep the markdown inside it
    parsed as markdown.
    """
    return wrapped(
        "reference-table",
        ["| Field | Type | Description |", "| --- | --- | --- |", *rows],
    )


def wrapped(class_name: str, lines: Sequence[str]) -> str:
    return "\n".join([f'<div className="{class_name}">', "", *lines, "", "</div>"])


# -----------------------------------------------------
# The model tree
# -----------------------------------------------------


def tree_html(ctx: Context, roots: Sequence[type], published: Set[type]) -> str:
    """The category's models as a tree, links down to the tables below it.

    Each model is drawn once, at its first occurrence, and every later
    appearance is a leaf noted as drawn above. A shape reached from two places
    is the normal case rather than the exception — Google Calendar's
    ``ConferenceSolutionKey`` hangs off both ``ConferenceSolution`` and
    ``CreateRequest`` — and redrawing its subtree at each one makes the tree
    claim more models than the category has.

    Drawn whole. An earlier version stopped at depth two and carried a ``+N``
    of what it had not drawn, which was wrong twice over: the counts
    double-counted a shared model, and nothing was actually hidden, since every
    model in the count has its own section further down the same page. What the
    cut saved was five lines. The box scrolls instead.

    Nested divs rather than a nested list. Mintlify's prose styles own ``li`` —
    its own bullet, its own padding, its own vertical rhythm — and a tree drawn
    with lists spends its life outbidding them.
    """
    drawn: Set[type] = set()

    def node(model: type) -> str:
        label = link_html(ctx, model.__name__, ctx.homes.get(model))
        children = [c for c in direct_children(model) if c in published]
        if model in drawn:
            # Marking it only when there is a subtree elsewhere: on a model with
            # no children, a leaf here and a leaf there say the same thing.
            note = ' <span className="tree-note">above</span>' if children else ""
            return f'<div className="tree-node">{label}{note}</div>'
        drawn.add(model)
        if not children:
            return f'<div className="tree-node">{label}</div>'
        inner = "".join(node(child) for child in children)
        return (
            f'<div className="tree-node">{label}'
            f'<div className="tree-children">{inner}</div>'
            f"</div>"
        )

    items = "".join(node(root) for root in roots)
    # The scroller is a child rather than the box itself, so the copy button
    # that model-tree.js hangs in the corner stays put while the tree scrolls.
    return (
        '<div className="model-tree">'
        f'<div className="model-tree-scroll">{items}</div>'
        "</div>"
    )


# -----------------------------------------------------
# One tool page
# -----------------------------------------------------


def code_sample(pack: str, tool: Tool) -> str:
    """The call a reader should copy, which is never curl.

    Required arguments are named and left as ellipses. A sample that invented
    plausible values would be a sample somebody pastes.

    Titled with a filename, as every block on the pack pages is. Mintlify falls
    back to the language when there is no title, and a header reading "Python"
    on a page inside a Python SDK's reference spends a line saying nothing.
    """
    required = tool.to_json_schema()["parameters"].get("required", [])
    args = ", ".join(f'"{name}": ...' for name in required)
    return (
        f"```python {pack}_{tool.name}.py\n"
        f"from charter.packs import {pack}\n\n"
        f"result = await {pack}.{tool.name}.ainvoke({{{args}}})\n"
        "```"
    )


def route_of(tool: Tool) -> str:
    """The tool's URL template, with placeholders spelled as the arguments are.

    ``gcalendar`` writes ``calendars/{calendar_id}/events`` while ``gmail``
    writes ``{userId}``; the LLM schema serialises both as camelCase. The
    template is normalised rather than the argument renamed — the page is an
    argument reference, and one snake_case name among camelCase ones reads as a
    different parameter. The wire's own spelling stays on the pack page's wire
    table.
    """
    normalised = re.sub(r"\{(\w+)\}", lambda m: "{" + to_camel(m.group(1)) + "}", tool.url_template)
    return "/" + normalised.lstrip("/")


def _placements(tool: Tool) -> Dict[str, str]:
    """Where each top-level argument goes, read off the wire schema's markers."""
    from charter.types.markers import Body, Query
    from charter.types.markers import Path as PathMarker

    out: Dict[str, str] = {}
    for name, field in tool.args_schema.model_fields.items():
        for marker in field.metadata:
            if isinstance(marker, PathMarker):
                out[to_camel(name)] = "path"
            elif isinstance(marker, Query):
                out[to_camel(name)] = "query"
            elif isinstance(marker, Body):
                out[to_camel(name)] = "body"
    return out


def preamble(tool: Tool, shared_route: Optional[str] = None) -> Optional[str]:
    """What the tool declares that no argument list can show.

    Scopes and pagination are properties of the endpoint rather than of any one
    field, and both change what a caller has to do — ask for the right grant,
    walk the cursor. Rendered above the arguments, from the declaration.
    """
    notes: List[str] = []
    if shared_route:
        notes.append(
            f"Posts a GraphQL document to `{tool.method} {shared_route}`, "
            "as every tool in this pack does."
        )
    if tool.scopes:
        notes.append("Requires " + ", ".join(f"`{scope}`" for scope in tool.scopes) + ".")
    if tool.pagination is not None:
        pagination = tool.pagination
        if pagination.page_param:
            notes.append(
                f"Pages by number: `{pagination.page_param}` with `{pagination.per_page_param}`."
            )
        else:
            notes.append(
                f"Pages by cursor: `{pagination.cursor_field}` is sent back as "
                f"`{pagination.cursor_param}`."
            )
    if tool.quota_cost is not None:
        notes.append(f"Costs {tool.quota_cost} against the provider's own quota.")
    if not notes:
        return None
    return "<Note>\n  " + " ".join(notes) + "\n</Note>"


_SECTIONS = [("path", "Path parameters"), ("query", "Query parameters"), ("body", "Body")]


# Above this, a tool costs more context than the task the model was given. Seven
# tools are over it, and every one is a write endpoint whose resource or union is
# genuinely that wide — so the answer is a projection at the call site, not a
# thinner schema in the pack.
_WIDE_SCHEMA_BYTES = 20_000


def _is_oneof(model: type) -> bool:
    """Whether a repeated model is a union of alternatives rather than a resource.

    `Sheet` and `Request` are both repeated models with fifteen-plus optional
    fields, and only one of them is a set of mutually exclusive choices. The
    difference is declared: a oneof carries the validator enforcing exactly one,
    so a `keep` example is only generated where keeping a subset means anything.
    """
    fields = model.model_fields
    if len(fields) < 10 or any(f.is_required() for f in fields.values()):
        return False
    return bool(model.__pydantic_decorators__.model_validators)


def _widest_union(tool: Tool) -> Optional[Tuple[str, int, List[str]]]:
    """The oneof a wide tool hides, as (field path, member count, first members).

    A batch endpoint puts every edit it supports behind one repeated field, and
    that field is what a reader narrows. Found rather than declared, so a pack
    that grows a union gets the right example without anyone editing this file.
    """
    best: Optional[Tuple[str, int, List[str]]] = None

    def consider(path: str, annotation: Any) -> None:
        nonlocal best
        item = _list_item_model(annotation)
        if item is None or not _is_oneof(item):
            return
        members = list(item.model_fields)
        if best is None or len(members) > best[1]:
            best = (path, len(members), members[:3])

    for name, field in tool.args_schema.model_fields.items():
        consider(name, field.annotation)
        # Docs wraps its union one level down, in `body.requests`. A top-level
        # scan finds Sheets' and misses the pack the feature was built for.
        nested = _model_of(field.annotation)
        if nested is not None:
            for sub, sub_field in nested.model_fields.items():
                consider(f"{name}.{sub}", sub_field.annotation)
    return best


def _peel(annotation: Any) -> Any:
    """``Optional[List[X]]`` -> ``X``, however the two are nested.

    Both orders occur, and handling only the outer one is how `sheets`, the
    `Optional[List[Sheet]]` holding most of a spreadsheet, went unseen.
    """
    args = get_args(annotation)
    origin = get_origin(annotation)
    if origin is not None and args:
        real = [a for a in args if a is not type(None)]
        if real and (origin is list or len(real) == 1):
            return _peel(real[0])
    return annotation


def _model_of(annotation: Any) -> Optional[type]:
    """The BaseModel a field is built from, through Optional and List."""
    peeled = _peel(annotation)
    return peeled if isinstance(peeled, type) and issubclass(peeled, BaseModel) else None


def _list_item_model(annotation: Any) -> Optional[type]:
    """The BaseModel a repeated field repeats, or None if it is not repeated."""
    inner = annotation
    if get_origin(inner) is not list:
        real = [a for a in get_args(inner) if a is not type(None)]
        inner = real[0] if len(real) == 1 else inner
    if get_origin(inner) is not list:
        return None
    return _model_of(inner)


def _heaviest_optional_branches(tool: Tool, limit: int = 3) -> List[str]:
    """The optional sub-objects costing the most, as dotted paths, largest first.

    A resource with no union is wide because of its branches. Those branches are
    rarely at the top: ``events_insert`` takes a required ``event``, and the
    weight is the fifteen models hanging off it. So this looks one level inside
    each top-level model too, and returns what ``drop`` would be given.

    Sized by their own rendered schema, so the example names the expensive branch
    rather than the first one declared.
    """
    sized: List[Tuple[int, str]] = []

    def consider(path: str, field: Any) -> None:
        if field.is_required():
            return
        model = _model_of(field.annotation)
        if model is not None:
            sized.append((len(json.dumps(model.model_json_schema())), path))

    for name, field in tool.args_schema.model_fields.items():
        consider(name, field)
        nested = _model_of(field.annotation)
        if nested is not None:
            for sub, sub_field in nested.model_fields.items():
                consider(f"{name}.{sub}", sub_field)

    sized.sort(reverse=True)
    ordered = [path for _, path in sized]
    leafward = [p for p in ordered if not any(q.startswith(f"{p}.") for q in ordered)]
    return leafward[:limit]


def _unique(tool: Tool, name: str) -> bool:
    """Whether a bare field name resolves to one path on this tool."""
    every = tool.paths(depth=None)
    return sum(1 for p in every if p == name or p.endswith(f".{name}")) == 1


def wide_schema_note(tool: Tool) -> Optional[str]:
    """What to do about a tool whose schema is larger than the task.

    Rendered from the measured size, so it appears exactly where it is true and
    disappears if the schema shrinks.
    """
    size = len(json.dumps(tool.to_json_schema()))
    if size < _WIDE_SCHEMA_BYTES:
        return None

    union = _widest_union(tool)
    if union is not None:
        path, count, sample = union
        why = f"because `{path}` carries {count} kinds of edit behind one method"
        names = [m if _unique(tool, m) else f"{path}.{m}" for m in sample]
        selector = "keep={" + ", ".join(f'"{m}"' for m in names) + "}"
        closing = f"Three of the {count} are kept here. Which ones your agent needs is yours to pick."
    else:
        why = "because it models the whole resource this endpoint writes"
        heavy = _heaviest_optional_branches(tool)
        if not heavy:
            return None
        selector = "drop={" + ", ".join(f'"{m}"' for m in heavy) + "}"
        closing = "Those are its heaviest branches by schema size, not a recommendation: which ones you can spare is yours to decide."

    return "\n".join(
        [
            "<Warning>",
            f"  This tool's JSON schema is {size // 1024} KB, {why}.",
            "  That is more context than most tasks. Narrow it at the call site",
            "  with [`Tool.derived`](/reference/tool#tool-derived):",
            "",
            "  ```python",
            f"  narrowed = {tool.pack}.{tool.name}.derived(",
            f'      name="{tool.name}_narrowed",',
            f"      {selector},",
            "  )",
            "  ```",
            "",
            f"  {closing} The tool underneath is unchanged.",
            "  See [Projections](/tools/projections).",
            "</Warning>",
        ]
    )


def _frontmatter_value(text: str) -> str:
    """One line of YAML, safe to sit inside double quotes.

    A tool description is prose written by a pack author, and a quotation mark
    in it — naming a literal argument such as ``mode="external_url"`` — closes
    the YAML string early and fails the whole docs build rather than that one
    page. Escaped here rather than banned there: the alternative is a rule about
    punctuation that nothing enforces until a release is cut.
    """
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def tool_page(ctx: Context, pack: str, tool: Tool, shared_route: Optional[str]) -> str:
    schema = tool.to_json_schema()["parameters"]
    properties: Dict[str, Any] = schema.get("properties", {})
    required = set(schema.get("required", []))
    placement = _placements(tool)
    pills = marker_map(tool.args_schema).get(tool.args_schema, {})

    base = tool.base_url
    server = "" if callable(base) else str(base).rstrip("/")
    route = f"{server}{route_of(tool)}"

    parts = [
        "---",
        f'title: "{tool.name}"',
        f'description: "{_frontmatter_value(tool.description)}"',
        # The pill beside the name in the sidebar. Mintlify drew it from the
        # OpenAPI operation before the reference moved to MDX, and a sidebar
        # that stopped saying which of four `issues_*` tools writes would be a
        # worse page list than the one it replaced.
        f'tag: "{tool.method}"',
        "---",
        "",
        _BANNER,
        "",
        f'<div className="tool-route">'
        f'<span className="tool-row-method" data-method="{tool.method}">{tool.method}</span>'
        f"<code>{jsx_string(route)}</code>"
        f"</div>",
        "",
        code_sample(pack, tool),
        "",
    ]

    note = preamble(tool, shared_route)
    if note:
        parts += [note, ""]

    wide = wide_schema_note(tool)
    if wide:
        parts += [wide, ""]

    grouped: Dict[str, Dict[str, Any]] = {"path": {}, "query": {}, "body": {}}
    for name, node in properties.items():
        grouped[placement.get(name, "body")][name] = node

    for key, heading in _SECTIONS:
        if not grouped[key]:
            continue
        parts += [f"## {heading}", "", table(field_rows(ctx, grouped[key], required, pills)), ""]

    if not any(grouped.values()):
        parts += ["This tool takes no arguments.", ""]

    return "\n".join(parts).rstrip() + "\n"


# -----------------------------------------------------
# One objects page
# -----------------------------------------------------


def objects_mdx(
    ctx: Context,
    title: str,
    roots: Sequence[type],
    models: Sequence[type],
    enums: Sequence[NamedEnum],
    defs: Dict[str, Dict[str, Any]],
    pills: Dict[type, Dict[str, List[Tuple[str, str]]]],
) -> str:
    """One category's objects and enums, as anchored tables under a tree.

    The tables are rendered before anything is emitted, because rendering is
    what discovers which enums the category reaches and which of them are homed
    here. Every named enum in the pack is offered and the filter runs at the
    end: the type modules declare aliases for parts of an API a pack has not
    covered yet, and a section for one of those is a table nothing links to.
    """
    published = set(models)
    body: List[str] = []

    for model in models:
        node = defs.get(f"{model.__name__}{_LLM_SUFFIX}") or defs.get(model.__name__)
        if node is None:
            continue
        body += [f"## {model.__name__}", ""]
        # Split on the first blank line, counting a whitespace-only line as
        # blank. Before 3.13 a docstring kept its source indentation, so the
        # "blank" line between a summary and its API Reference was the file's
        # indent rather than an empty string and this split found nothing to
        # cut on; 3.13 strips that indentation (gh-81283) and the same
        # docstring suddenly has a paragraph break. Matching either way keeps
        # the generated page identical on every supported version.
        doc = _PARAGRAPH_BREAK.split((model.__doc__ or "").strip())[0]
        if doc:
            body += [mdx(doc), ""]
        rows = field_rows(
            ctx, node.get("properties", {}), set(node.get("required", [])), pills.get(model, {})
        )
        body += [table(rows) if rows else "This object has no settable fields.", ""]

    for enum in enums:
        if enum.values not in ctx.used or ctx.enum_homes.get(enum.values) != ctx.category:
            continue
        values = [f"| {code(value)} |" for value in enum.values]
        body += [
            f"## {enum.name}",
            "",
            wrapped("enum-table", ["| Value |", "| --- |", *values]),
            "",
        ]

    if not body:
        return ""

    head = [
        "---",
        'title: "Objects"',
        f'description: "Every object and enum the {title} tools accept."',
        "---",
        "",
        _BANNER,
        "",
    ]
    if roots:
        head += ["## Model tree", "", tree_html(ctx, roots, published), ""]

    return "\n".join(head + body).rstrip() + "\n"


# -----------------------------------------------------
# One pack
# -----------------------------------------------------


def _shared_route(tools: Sequence[Tool]) -> Optional[str]:
    """The one endpoint a GraphQL pack posts every tool to, if there is one."""
    routes = {(tool.method, route_of(tool)) for tool in tools}
    if len(routes) == 1 and len(tools) > 1:
        return next(iter(routes))[1]
    return None


def _defs_for(tools: Sequence[Tool]) -> Dict[str, Dict[str, Any]]:
    """Every ``$defs`` entry the pack's tools produce, merged by name.

    Two tools deriving the same wire model do **not** always produce the same
    view of it. Linear narrows a filter differently depending on where it sits:
    ``IssueFilter`` reached as an argument keeps forty-one conditions, and the
    same type reached as a relation - ``DocumentFilter.issue`` - keeps the three
    that identify an issue. Both are correct, and the reference documents the
    type once, so it documents the widest view: every narrower one is a subset of
    it, and a field that links to the type from a narrow context still finds
    every field it can name.

    Firecrawl's ``Format`` and friends are genuinely different classes that share
    a name. Those are keyed by class below; this map is only consulted through
    ``Context.models``, which is.
    """
    out: Dict[str, Dict[str, Any]] = {}
    for tool in tools:
        for name, body in tool.to_json_schema()["parameters"].get("$defs", {}).items():
            existing = out.get(name)
            if existing is None or len(body.get("properties") or {}) > len(
                existing.get("properties") or {}
            ):
                out[name] = body
    return out


def pack_pages(pack: str) -> Dict[str, str]:
    """Every page one pack publishes, as ``{path relative to docs/: body}``.

    A model is published on the first category page whose tools reach it, and
    linked from every other. Two rules follow from that and are worth stating,
    because the obvious alternative fails on a real pack:

    Home by *use*, not by where the model is declared. A model homed on the page
    of the module that declares it can land on a page whose tools never build
    its schema — gdocs keeps every type in one module and renders flat — and
    then there is a link with no table under it.

    Publish only what the LLM view emits. ``model_tree`` walks the wire model,
    which still carries the ``response_only`` fields the view drops; Google
    Calendar's ``Creator`` is one of them. Those are types no caller can set, so
    they get no section, and nothing may link to them either.
    """
    module = pack_module(pack)
    tools: List[Tool] = list(module.TOOLS)
    groups = categorised(pack, tools)
    shared = _shared_route(tools)
    enums = named_enums(pack)

    homes: Dict[type, Optional[str]] = {}
    published: Dict[Optional[str], List[type]] = {}
    # ``$defs`` name -> wire model, per category. Two classes in one pack can
    # share a name — firecrawl's ``search`` and ``scrape`` each declare a
    # ``Format`` — so a pack-wide map would resolve one page's refs to the
    # other page's model.
    def_names: Dict[Optional[str], Dict[str, type]] = {}

    for slug, category_tools in groups:
        names: Dict[str, type] = {}
        mine: List[type] = []
        for tool in category_tools:
            defs = tool.to_json_schema()["parameters"].get("$defs", {})
            emitted = {name.removesuffix(_LLM_SUFFIX): name for name in defs}
            for model in model_tree(tool.args_schema):
                if model is tool.args_schema:
                    continue
                key = emitted.get(model.__name__)
                if key is None:
                    continue
                names.setdefault(key, model)
                if model not in homes:
                    homes[model] = slug
                    mine.append(model)
        def_names[slug] = names
        published[slug] = mine

    pills: Dict[type, Dict[str, List[Tuple[str, str]]]] = {}
    for tool in tools:
        pills.update(marker_map(tool.args_schema))

    enum_homes: Dict[Tuple[str, ...], Optional[str]] = {}
    contexts: Dict[Optional[str], Context] = {}
    pages: Dict[str, str] = {}

    for slug, category_tools in groups:
        ctx = Context(
            pack=pack,
            category=slug,
            enums=enums,
            enum_homes=enum_homes,
            models=def_names[slug],
            homes=homes,
        )
        contexts[slug] = ctx
        directory = f"packs/{pack}/{slug}" if slug else f"packs/{pack}"
        for tool in category_tools:
            pages[f"{directory}/{tool.name}.mdx"] = tool_page(ctx, pack, tool, shared)

    for slug, category_tools in groups:
        ctx = contexts[slug]
        # From here the objects page is what is being written, so a link to a
        # heading on it is an anchor rather than a round trip through the router.
        ctx.page = objects_page(pack, slug)
        directory = f"packs/{pack}/{slug}" if slug else f"packs/{pack}"
        models = published[slug]

        roots: List[type] = []
        for tool in category_tools:
            for child in direct_children(tool.args_schema):
                if child not in roots and child in set(models):
                    roots.append(child)

        body = objects_mdx(
            ctx,
            category_title(pack, slug) if slug else _pack_title(pack),
            roots,
            models,
            list(enums.values()),
            _defs_for(category_tools),
            pills,
        )
        if body:
            pages[f"{directory}/objects.mdx"] = body

    return pages


# -----------------------------------------------------
# Navigation
# -----------------------------------------------------


def _pack_title(pack: str) -> str:
    """The pack's display name, read off its overview page's frontmatter."""
    text = (PACK_DOCS / f"{pack}.mdx").read_text()
    match = re.search(r'^title:\s*"(.+?)"', text, re.MULTILINE)
    return match.group(1) if match else pack


def pack_nav(pack: str) -> Dict[str, Any]:
    module = pack_module(pack)
    tools = list(module.TOOLS)
    groups = categorised(pack, tools)

    pages: List[Any] = [f"packs/{pack}"]
    published = pack_pages(pack)
    for slug, category_tools in groups:
        directory = f"packs/{pack}/{slug}" if slug else f"packs/{pack}"
        leaves = [f"{directory}/{tool.name}" for tool in category_tools]
        if f"{directory}/objects.mdx" in published:
            leaves.append(f"{directory}/objects")
        if slug is None:
            pages.extend(leaves)
        else:
            pages.append({"group": category_title(pack, slug), "pages": leaves})

    return {"group": _pack_title(pack), "expanded": False, "pages": pages}


def packs_tab() -> Dict[str, Any]:
    oauth, api_key = [], []
    for pack in PACKS:
        tools = list(pack_module(pack).TOOLS)
        target = oauth if tools[0].credential_provider is not None else api_key
        target.append(pack_nav(pack))
    return {
        "tab": "Packs",
        "pages": [
            "packs/overview",
            {"group": "OAuth packs", "pages": oauth},
            {"group": "API-key packs", "pages": api_key},
        ],
    }


# Where every tool page lived while the pack reference was one OpenAPI document
# per pack: ``packs/<pack>/tools/<tool>``, from the tag on every operation.
_LEGACY_SEGMENT = "tools"


def tool_redirects() -> List[Dict[str, str]]:
    """From the tag-derived path each tool page used to have, to where it is now.

    These pages are what the pack pages have linked to since the packs shipped,
    and a reader who bookmarked one should not meet a 404 because the reference
    changed how it groups things.
    """
    out = []
    for pack in PACKS:
        for tool in pack_module(pack).TOOLS:
            source = f"/packs/{pack}/{_LEGACY_SEGMENT}/{tool.name}"
            destination = tool_page_path(pack, tool)
            if source != destination:
                out.append({"source": source, "destination": destination})
    return out


def render_docs_json() -> str:
    config = json.loads((DOCS / "docs.json").read_text())
    tabs = config["navigation"]["tabs"]
    for index, tab in enumerate(tabs):
        if tab["tab"] == "Packs":
            tabs[index] = packs_tab()
            break

    # ``api`` configured Mintlify's OpenAPI renderer — a hidden playground,
    # collapsed nested params, and which ``x-charter-*`` keys became pills. No
    # pack ships an OpenAPI document any more, so all of it is inert.
    config.pop("api", None)

    kept = [
        redirect
        for redirect in config.get("redirects", [])
        if f"/{_LEGACY_SEGMENT}/" not in redirect["source"]
    ]
    config["redirects"] = kept + tool_redirects()
    return json.dumps(config, indent=2) + "\n"


# -----------------------------------------------------
# Driving it
# -----------------------------------------------------


def all_pages() -> Dict[str, str]:
    pages: Dict[str, str] = {}
    for pack in PACKS:
        pages.update(pack_pages(pack))
    return pages


def _generated_paths() -> List[Path]:
    """Every file previously written here, so a removed tool's page goes away."""
    out = []
    for path in PACK_DOCS.rglob("*.mdx"):
        if path.parent != PACK_DOCS and _BANNER in path.read_text():
            out.append(path)
    return out


def main(argv: Sequence[str]) -> int:
    check = "--check" in argv
    pages = all_pages()
    config = render_docs_json()

    wanted = {DOCS / path: body for path, body in pages.items()}
    stale: List[str] = []

    for path in _generated_paths():
        if path not in wanted:
            stale.append(f"{path.relative_to(DOCS)} (removed)")
            if not check:
                path.unlink()

    for path, body in sorted(wanted.items()):
        current = path.read_text() if path.exists() else None
        if current == body:
            continue
        stale.append(str(path.relative_to(DOCS)))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)

    docs_json = DOCS / "docs.json"
    if docs_json.read_text() != config:
        stale.append("docs.json")
        if not check:
            docs_json.write_text(config)

    if not check:
        for pack in PACKS:
            legacy = PACK_DOCS / f"{pack}.openapi.json"
            if legacy.exists():
                legacy.unlink()

    if check and stale:
        print(f"stale pack reference: {', '.join(stale[:8])}", file=sys.stderr)
        print(f"run: uv run python {_SCRIPT}", file=sys.stderr)
        return 1

    verb = "stale" if check else "rewritten"
    print(f"{len(pages)} pack reference pages checked, {len(stale)} {verb}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
